### ISSUE TITLE
High power consumption during deep sleep

### ISSUE THREAD

**Issue by yareky** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#8]
After removing the red led and connecting 3.3V power supply directly to the 3.3V pin I measured ~1mA during deep sleep.
According to the datasheet I expected about 5uA or something way below 1mA.
Any suggestions how to decrease power usage?
I've also tried to pull-up manually flash CS pin to the 3.3V power supply because VDD_SPI ping seems to be floating during deep sleep but without success

**Comment by gigamegawatts** [comment]
I was wondering about that too, but I don't have the equipment needed to get an accurate measurement of power usage during deep sleep.

I had assumed that flash was powered during deep sleep, since that's a problem with most other LilyGo ESP32 boards.  

However, maybe it's fixable here.  According to the datasheet "VDD_SPI can be powered off via software to minimize the current leakage of flash in Deep-sleep mode".  I haven't found any examples on how to do that, or any evidence that the ESP-IDF code already does that.

It would be nice if someone at LilyGo would answer your question, but you might get a faster answer if you ask about it on the ESP-IDF Github.

Based on the Technical Reference, my guess is that powering off VDD_SPI involves the register settings for IO_MUX_GPIO11_REG, which are listed on page 169 in v0.3 of the Technical Reference.  That register is PERIPHS_IO_MUX_VDD_SPI_U in io_mux_reg.h.  I decided not to play around with it, since the code in sleep_modes.c is complex and it's probably not as simple as setting a flag or two in that register.

**Comment by al1fch** [comment]
> I had assumed that flash was powered during deep sleep, since that's a problem with most other LilyGo ESP32 boards.

Scope shows a floating pin (near the ground) for the Windbond Flash CS (pin, 1) so Flash is not fully OFF during deepsleep

**Comment by yareky** [comment]
> I'll try with a pull-up resistor on this Chip Select pin as done on some other boards with good result (LOLIN 32 Lite)
As I mentioned I tried, but without any significant result.

> Based on the Technical Reference, my guess is that powering off VDD_SPI involves the register settings for IO_MUX_GPIO11_REG, 
Thanks for this note, I will check the manual!
I tried to set GPIO_NUM_14 (SPICS0) in gpio_config but also without any success.

**Comment by al1fch** [comment]
29µA during deep-sleep before any modification on my board and/or  in code (TimerWakeUp.ino)
not so bad !!  

Board is V1.1 version( date 20210716), core 2.0.0-RC2 version

**Comment by yareky** [comment]
> 29.8 µA during deep-sleep before any modification on my board and/or in code (TimerWakeUp.ino)
29.8 µA with red power led on?!

I've tried your setup using Arduino IDE, besides not correctly working serial port with 40MHz clock, I did not get any better results. Nothing close to the 30uA

**Comment by al1fch** [comment]
A 'little change' ,on my board  : **power red led removed !!**, as soon as i got the board in my hands !!

How is deep current current measured ?   As a retired electronic teacher I do :
1)flash  the chip with code for ipermanent deep-sleep 
2) put a good multimeter on µA calibre, multimeter  shunted during chip's boot, shunt removed after boot time
(Of course multimeter , in current measure modeis in serial with 3.7V battery
... So I'm confident with  30µA 

Same method gave me good results (coherent with many other guys ) for MSP430, ESP8266, ESP32 ... chips in sleep mode

**Comment by ekawahyu** [comment]
I must agree with @yareky that there is ~1 mA in deep sleep mode. Power LED is removed, use TimerWakeUp.ino to wake up every 60 seconds, my measurement is repeatable at 1.15 mA constant draw in deep sleep mode. What am I missing here. My board is the exact look of this link below, I don't know if there is other version/clone out there?

https://www.tindie.com/products/lilygo/lilygo-ttgo-t-oi-plus-risc-v-esp32-c3/

**Comment by LilyGO** [comment]
Power LED removed. Use this [sketch](https://github.com/Xinyuan-LilyGO/LilyGo-T-OI-PLUS/tree/main/example/deepsleep). Low power consumption measured
![AAF9809AD033003DB1F261107E9F5E37](https://user-images.githubusercontent.com/31160602/138224373-a50e5520-75a1-47de-8fd4-974d1bd50c35.png)

**Comment by LilyGO** [comment]
I also use Arduino-esp v2.0.0

**Comment by ekawahyu** [comment]
@LilyGO I just noticed (but not sure) that the photo shows V1.2 and mine is V1.1. Could you provide information of the diff between these two?

**Comment by LilyGO** [comment]
Modified antenna and several capacitance inductor parameters, others are the same.
Are you sure your power indicator (red) has been removed?

**Comment by ekawahyu** [comment]
@yareky Your board does not seem to include 3V3 regulator, could you point me to the schematic/layout of this hardware version?

**Comment by mailinger-mate** [comment]
Hello @yareky & @ekawahyu!

I am not en expert on working with PCBs so I would like to ask for your help with #21.
How can i have external power with backup battery and charging while preserving low power consumption in deep sleep?

Thank you!
